# Use C++ 2011.  Compile for debugging (-g) with warnings.
CXXFLAGS = -std=c++11 -g -Wall -Wextra


# This rule makes the binary program from .o files.
# (.o files are made from .cc files using a rule further down.)
# The command uses some special variables:
#   $@  -- the name of the target
#   $^  -- the names of all dependencies (the .o files listed after ":")

GameOfLife:	GameOfLife_main.o
	g++ -o $@ $^

# These rules just give additional dependencies.
# They don't have a command, because there are default commands to
# compile .cc to .o.  (They use the flag variables defined above.)

GameOfLife_main.o:		GameOfLife.h

